name: main branch SNAPSHOT build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    - name: Compile
      run: mvn -B clean compile -f pom.xml

    - name: Run tests
      run: mvn -B verify -f pom.xml

    - name: Build artifacts
      run: mvn -B package -Dmaven.test.skip=true -f pom.xml

    - name: Deploy artifacts to repository
      run: mvn -B deploy -Dmaven.test.skip=true -f pom.xml -s $GITHUB_WORKSPACE/.github/maven-settings.xml
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
